### PR TITLE
Add support for symfony Controllers

### PR DESCRIPTION
**Pull request by mzk**
`getClassName` returned for example AccountController, not `Controller`. 

```
vendor/shipmonk-php-code-checker/vendor/bin/phpstan analyse -l 6 -c phpstan.neon src/Fulfillment/Bundle/AccountApiBundle/Controller/AccountController.php
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------------ 
  Line   AccountController.php                                 
 ------ ------------------------------------------------------ 
  44     Service "foobar" is not registered in the container.  
  45     Call to an undefined method object::callNo().         
 ------ ------------------------------------------------------ 
```
cc https://github.com/ShipMonk/shipmonk/pull/1668

### CODE REVIEW

**Comment by lookyman** [comment]
Looks good, although I am not sure what defining the Controller class in tests does with autoloading.. I'll check it and get back to you.

**Comment by mzk** [comment]
We use it use in our project with a lot of dependencies and there is no problem with the autoloader. But rather, try it for sure.

**Comment by mzk** [comment]
@lookyman pull request was updated, added a fix. `Service "" is not registered in the container.`

**Comment by lookyman** [comment]
Thank you!

**Pull request merged**
